### ISSUE TITLE
Feature Request: Anchors (Auto-Generated)

### ISSUE THREAD

**Issue by BoldestDungeon** [BoldestDungeon/wildermyth-drauven-pcs#621] opened 2024-06-12 22:52 UTC
A new Comic Update Request has been made through Discord: 
[Anchors](https://discord.com/channels/968305036700549192/1250583286179168327)

_If this feature is accepted, please replace this auto-generated message with a proper summary of the task requirements._

**Comment by justEthaniguess** [comment] 2024-06-12 23:03
This is a duplicate of an existing issue, so I'll close it.

**Closed by justEthaniguess** 2024-06-12 23:03 UTC
Labels: Comic, Auto-Generated
